#!/usr/bin/bash

echo "--------------- RUNNING TESTS WITH SAFETY CHECKS ---------------"
echo "----------------------------------------------------------------"
cargo test --features safety_checks --workspace


echo "--------------- RUNNING TESTS WITHOUT SAFETY CHECKS ------------"
echo "----------------------------------------------------------------"
cargo test --workspace