[package]
name = "lib_x86"
version = "0.1.0"
edition = "2024"

[dependencies]
lib_types = { workspace = true }
lib_utils = { workspace = true }


[lib]
path = "src/lib_x86.rs"


[features]
default = []
safety_checks = ["lib_types/safety_checks", "lib_utils/safety_checks"]